/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clinicamedica;

/**
 *
 * @author Gabri
 */
public class RegistrodeRetorno extends javax.swing.JFrame {

    /**
     * Creates new form RegistrodeRetorno
     */
    public RegistrodeRetorno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        txtAdministrativo = new javax.swing.JMenu();
        menuCadastroFuncionarios = new javax.swing.JMenuItem();
        menuCadastroUsuarios = new javax.swing.JMenuItem();
        menuCadastroEspecialidades = new javax.swing.JMenuItem();
        menuCadastroMedicos = new javax.swing.JMenuItem();
        menuCadastroConvenios = new javax.swing.JMenuItem();
        txtAgendamento = new javax.swing.JMenu();
        menuCadastroPaciente = new javax.swing.JMenuItem();
        menuAgendarConsulta = new javax.swing.JMenuItem();
        menuRegistroRetorno = new javax.swing.JMenuItem();
        menuCancelamentoConsulta = new javax.swing.JMenuItem();
        txtAtendimento = new javax.swing.JMenu();
        menuProntuarioPaciente = new javax.swing.JMenuItem();
        menuRegistroAtendimento = new javax.swing.JMenuItem();
        menuReceituario = new javax.swing.JMenuItem();
        menuExames = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        txtAdministrativo1 = new javax.swing.JMenu();
        menuCadastroFuncionarios1 = new javax.swing.JMenuItem();
        menuCadastroUsuarios1 = new javax.swing.JMenuItem();
        menuCadastroEspecialidades1 = new javax.swing.JMenuItem();
        menuCadastroMedicos1 = new javax.swing.JMenuItem();
        menuCadastroConvenios1 = new javax.swing.JMenuItem();
        txtAgendamento1 = new javax.swing.JMenu();
        menuCadastroPaciente1 = new javax.swing.JMenuItem();
        menuAgendarConsulta1 = new javax.swing.JMenuItem();
        menuRegistroRetorno1 = new javax.swing.JMenuItem();
        menuCancelamentoConsulta1 = new javax.swing.JMenuItem();
        txtAtendimento1 = new javax.swing.JMenu();
        menuProntuarioPaciente1 = new javax.swing.JMenuItem();
        menuRegistroAtendimento1 = new javax.swing.JMenuItem();
        menuReceituario1 = new javax.swing.JMenuItem();
        menuExames1 = new javax.swing.JMenuItem();
        menuSair1 = new javax.swing.JMenu();

        txtAdministrativo.setText("Administrativo");

        menuCadastroFuncionarios.setText("Cadastro de Funcionários");
        menuCadastroFuncionarios.setToolTipText("");
        txtAdministrativo.add(menuCadastroFuncionarios);

        menuCadastroUsuarios.setText("Cadastro de Usuários");
        txtAdministrativo.add(menuCadastroUsuarios);

        menuCadastroEspecialidades.setText("Cadastro de Especialidades");
        txtAdministrativo.add(menuCadastroEspecialidades);

        menuCadastroMedicos.setText("Cadastro de Médicos");
        txtAdministrativo.add(menuCadastroMedicos);

        menuCadastroConvenios.setText("Cadastro de Convênios");
        txtAdministrativo.add(menuCadastroConvenios);

        jMenuBar2.add(txtAdministrativo);

        txtAgendamento.setText("Agendamento");

        menuCadastroPaciente.setText("Cadastro de Pacientes");
        menuCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPacienteActionPerformed(evt);
            }
        });
        txtAgendamento.add(menuCadastroPaciente);

        menuAgendarConsulta.setText("Agenda de Consulta");
        txtAgendamento.add(menuAgendarConsulta);

        menuRegistroRetorno.setText("Registro de Retorno");
        txtAgendamento.add(menuRegistroRetorno);

        menuCancelamentoConsulta.setText("Cancelamento de Consulta");
        txtAgendamento.add(menuCancelamentoConsulta);

        jMenuBar2.add(txtAgendamento);

        txtAtendimento.setText("Atendimento");

        menuProntuarioPaciente.setText("Prontuário do Paciente");
        txtAtendimento.add(menuProntuarioPaciente);

        menuRegistroAtendimento.setText("Registro de Atendimento");
        txtAtendimento.add(menuRegistroAtendimento);

        menuReceituario.setText("Receituário");
        txtAtendimento.add(menuReceituario);

        menuExames.setText("Exames");
        txtAtendimento.add(menuExames);

        jMenuBar2.add(txtAtendimento);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar2.add(menuSair);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 115, 115));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1099, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        txtAdministrativo1.setText("Administrativo");

        menuCadastroFuncionarios1.setText("Cadastro de Funcionários");
        menuCadastroFuncionarios1.setToolTipText("");
        txtAdministrativo1.add(menuCadastroFuncionarios1);

        menuCadastroUsuarios1.setText("Cadastro de Usuários");
        txtAdministrativo1.add(menuCadastroUsuarios1);

        menuCadastroEspecialidades1.setText("Cadastro de Especialidades");
        txtAdministrativo1.add(menuCadastroEspecialidades1);

        menuCadastroMedicos1.setText("Cadastro de Médicos");
        txtAdministrativo1.add(menuCadastroMedicos1);

        menuCadastroConvenios1.setText("Cadastro de Convênios");
        txtAdministrativo1.add(menuCadastroConvenios1);

        jMenuBar1.add(txtAdministrativo1);

        txtAgendamento1.setText("Agendamento");

        menuCadastroPaciente1.setText("Cadastro de Pacientes");
        menuCadastroPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPaciente1ActionPerformed(evt);
            }
        });
        txtAgendamento1.add(menuCadastroPaciente1);

        menuAgendarConsulta1.setText("Agenda de Consulta");
        txtAgendamento1.add(menuAgendarConsulta1);

        menuRegistroRetorno1.setText("Registro de Retorno");
        txtAgendamento1.add(menuRegistroRetorno1);

        menuCancelamentoConsulta1.setText("Cancelamento de Consulta");
        txtAgendamento1.add(menuCancelamentoConsulta1);

        jMenuBar1.add(txtAgendamento1);

        txtAtendimento1.setText("Atendimento");

        menuProntuarioPaciente1.setText("Prontuário do Paciente");
        txtAtendimento1.add(menuProntuarioPaciente1);

        menuRegistroAtendimento1.setText("Registro de Atendimento");
        txtAtendimento1.add(menuRegistroAtendimento1);

        menuReceituario1.setText("Receituário");
        txtAtendimento1.add(menuReceituario1);

        menuExames1.setText("Exames");
        txtAtendimento1.add(menuExames1);

        jMenuBar1.add(txtAtendimento1);

        menuSair1.setText("Sair");
        menuSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSair1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPacienteActionPerformed
        new CadastrodePacientes().setVisible(true);
    }//GEN-LAST:event_menuCadastroPacienteActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // Menu Sair
        this.dispose();
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCadastroPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPaciente1ActionPerformed
        new CadastrodePacientes().setVisible(true);
    }//GEN-LAST:event_menuCadastroPaciente1ActionPerformed

    private void menuSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSair1ActionPerformed
        // Menu Sair
        this.dispose();
    }//GEN-LAST:event_menuSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrodeRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrodeRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrodeRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrodeRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrodeRetorno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAgendarConsulta;
    private javax.swing.JMenuItem menuAgendarConsulta1;
    private javax.swing.JMenuItem menuCadastroConvenios;
    private javax.swing.JMenuItem menuCadastroConvenios1;
    private javax.swing.JMenuItem menuCadastroEspecialidades;
    private javax.swing.JMenuItem menuCadastroEspecialidades1;
    private javax.swing.JMenuItem menuCadastroFuncionarios;
    private javax.swing.JMenuItem menuCadastroFuncionarios1;
    private javax.swing.JMenuItem menuCadastroMedicos;
    private javax.swing.JMenuItem menuCadastroMedicos1;
    private javax.swing.JMenuItem menuCadastroPaciente;
    private javax.swing.JMenuItem menuCadastroPaciente1;
    private javax.swing.JMenuItem menuCadastroUsuarios;
    private javax.swing.JMenuItem menuCadastroUsuarios1;
    private javax.swing.JMenuItem menuCancelamentoConsulta;
    private javax.swing.JMenuItem menuCancelamentoConsulta1;
    private javax.swing.JMenuItem menuExames;
    private javax.swing.JMenuItem menuExames1;
    private javax.swing.JMenuItem menuProntuarioPaciente;
    private javax.swing.JMenuItem menuProntuarioPaciente1;
    private javax.swing.JMenuItem menuReceituario;
    private javax.swing.JMenuItem menuReceituario1;
    private javax.swing.JMenuItem menuRegistroAtendimento;
    private javax.swing.JMenuItem menuRegistroAtendimento1;
    private javax.swing.JMenuItem menuRegistroRetorno;
    private javax.swing.JMenuItem menuRegistroRetorno1;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSair1;
    private javax.swing.JMenu txtAdministrativo;
    private javax.swing.JMenu txtAdministrativo1;
    private javax.swing.JMenu txtAgendamento;
    private javax.swing.JMenu txtAgendamento1;
    private javax.swing.JMenu txtAtendimento;
    private javax.swing.JMenu txtAtendimento1;
    // End of variables declaration//GEN-END:variables
}
